{
    'name': 'Bahia Personnel Management',
    'category': 'Human Resources',
    'sequence': 25,
    'summary': 'Jobs, Recruitment, Applications, Job Interviews, Surveys',
    'description': 'Personnel Management Information for Bahia',
    'author': 'Datagenesis',
    'depends': ['hr','mail', 'resource', 'board','hr_recruitment'],
    'data': [
	     'views/hr_employee_checklist_documents.xml',
	     'views/hr_recruitment_view.xml',
             'views/hr_recruitment_seabased_menu.xml',
             'views/hr_recruitment_dialog.xml',
             #'reports/hr_recruitment_base_report.xml',
             'reports/hr_personnel_report_menu.xml',
             'reports/hr_personnel_disembarkation_report_menu.xml',
             'reports/hr_personnel_embarkation_report_menu.xml',
             'reports/hr_personnel_signonoff_report_menu.xml',
             'reports/hr_personnel_active_onboard_with_relative.xml',
             'reports/reports/personnel_active_on_board.xml',
             'reports/reports/hr_disembarkation_report.xml',
             'reports/reports/hr_embarkation_report.xml',
             'reports/reports/hr_signonoff_report.xml',
             'reports/reports/hr_personnel_active_onboard_with_relative_report.xml',
             'views/hr_recruitment_degree.xml',
    	     'security/ir.model.access.csv',
             'data/ir_sequence.xml'],
    'css': ['static/src/css/hr.css'],
    'application': True,
}
#'data': ['hr_recruitment_view.xml','views/hr_recruitment_personnel_view.xml'],
#'security/ir.model.access.csv'

